### ISSUE TITLE
Consult some problems

### ISSUE THREAD

**Issue by buzhongyaoname** [din14970/pyMatchSeries#6]
Thanks for your help. I am just a beginner. So I have some problems want to consult you. Thanks for your answer yesterday. I can run the pyMatchSeries in my computer. However, the final output is a file with hSpy format. I do not know how to open the file and what I can get from it. 

Next I want to run the examples code in the https://github.com/berkels/match-series. However, I meet a new problem as illustrated in the following figure.
![image](https://user-images.githubusercontent.com/107195821/173190325-b2afc969-1dc2-4438-996e-a8fc2e05c445.png)

To be honest, I want to  find a software or code to deal with STEM data. For example, In ferroelectric materials, I want to get the atmoic displacement map, as shown in the following figure.
![image](https://user-images.githubusercontent.com/107195821/173190052-1f92f9e1-9e65-4e4b-bd00-18f78b5bd5e0.png)
DOI: 10.1103/PhysRevLett.125.047601

Finally, thanks your great job again. And if I have expressed wrong, please forgive me.

**Comment by din14970** [comment]
You should look into the hyperspy ecosystem. https://hyperspy.org/hyperspy-doc/current/index.html . the HSPY format is the default format for saving/loading data in Hyperspy, it's a convenient and transparant format based on hdf5 files. You can explore the interior with hdfview https://www.hdfgroup.org/downloads/hdfview/. For finding atomic column peaks and displacements maybe you find what you need in atomap https://atomap.org/. 

The issue you encounter with matchseries seems more related to a misspelled filename or something. Should it not be text.param? Not sure.

**Comment by din14970** [comment]
@buzhongyaoname was your issue resolved in the end?

**Comment by din14970** [comment]
I'm closing this for now, please reopen if necessary.
