### ISSUE TITLE
Error when run ‘calculation.run()’

### ISSUE THREAD

**Issue by PhysXu** [din14970/pyMatchSeries#7]
have solved

**Comment by din14970** [comment]
your images are very very small, 64x64, so you should not have to do registration at very high levels (power of 2). For some reason it's starting at level 6, so something went wrong creating the config file, because 2^6 is much larger than the number of pixels you have. From the output it seems you already have some folder with data and some config file. Perhaps delete that entire folder created by instantiating `MatchSeries` and try again. If that doesn't work, maybe share the generated config file here, it might be a bug that the levels are not correctly set.

**Comment by PhysXu** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Hi,    Thanks very much for the reply.    For some reasons, I can not access the Gihub website these days, so I response the email directly.    I confronted a new error when running MatchSeries response codes, please seeing below:        I do not know what happens and how to solve it.Following your suggestions, I put the generated config file in the attachment. Hope it can help to figure out the issue.I also attached my data, the dm3. file.       Any reply will be appreciated very much.
    
        
            
        
    Best,Mingquan
    
         
        
            
        
    
     

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            Niels ***@***.***>
            
        
      
      
        
         Date 
        
        
        10/20/2022 03:58
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [din14970/pyMatchSeries] Error when run ‘calculation.run()’ (Issue #7)
        
      
    
  
  
your images are very very small, 64x64, so you should not have to do registration at very high levels (power of 2). For some reason it's starting at level 6, so something went wrong creating the config file, because 2^6 is much larger than the number of pixels you have. From the output it seems you already have some folder with data and some config file. Perhaps delete that entire folder created by instantiating MatchSeries and try again. If that doesn't work, maybe share the generated config file here, it might be a bug that the levels are not correctly set.

**Comment by din14970** [comment]
Unfortunately it seems attachments are not forwarded in this way. I also don't see any images. Please copy paste pure text from errors and code in between \``` YOUR TEXT HERE \``` ticks. For sharing files, please upload them to a shared drive or something, e.g. google drive, and share the link.

**Comment by PhysXu** [comment]
Hi, I also tried a dataset with a size of 1024x1024 pixels, and get a similar error:
![image](https://user-images.githubusercontent.com/35793078/197913445-282f1e9d-2242-440d-824a-5d90611594e4.png)
......
![image](https://user-images.githubusercontent.com/35793078/197913646-4a9ae831-d349-417e-9f13-8a6035c7572e.png)

The attachment is the generated config file:
[config.zip](https://github.com/din14970/pyMatchSeries/files/9865195/config.zip)

**Comment by PhysXu** [comment]
Hi, now I can go through the “calculation.run()” by using the default parameters:
![image](https://user-images.githubusercontent.com/35793078/198507224-56ce5b81-e42d-4ba0-a8da-54913e4423d2.png)
......
But have a problem when applying deformations to my spectrum image data, it always tells me an error:
![image](https://user-images.githubusercontent.com/35793078/198509582-29e3176b-0b23-43cf-9421-50343b560ad3.png)
......
My data is a time-series SI with the frame of 10, but the codes cannot recognize it.

How to solve it?

**Comment by PhysXu** [comment]
> Hi, now I can go through the “calculation.run()” by using the default parameters: ![image](https://user-images.githubusercontent.com/35793078/198507224-56ce5b81-e42d-4ba0-a8da-54913e4423d2.png) ...... But have a problem when applying deformations to my spectrum image data, it always tells me an error: ![image](https://user-images.githubusercontent.com/35793078/198509582-29e3176b-0b23-43cf-9421-50343b560ad3.png) ...... My data is a time-series SI with the frame of 10, but the codes cannot recognize it.
> 
> How can I get the deformation? If I can get this, I could apply it to the 4D spectrum data along the energy channel axis by loops.

I found a method, but not sure it is correct:
![image](https://user-images.githubusercontent.com/35793078/198530290-67e335ec-dc3b-4102-a541-4215388501f3.png)
Any reply will be appreciated!

**Comment by PhysXu** [comment]
I found a method to solve the issue about my time-series SI data above
Here is my codes:
![image](https://user-images.githubusercontent.com/35793078/198530694-14f20487-d17d-44ee-995d-8c0b97a42e8e.png)
........
But I am not sure it is correct.
Any reply will be appreciated!

**Comment by din14970** [comment]
Sorry for the belated reply.

In the first case, the issue is probably that you set `numTemplates` to 50, when you only have 10 images. You use this when you want to limit the number of images (i.e. if you have more).

In the last case, the issue is that it expects the spectrum map to be of shape [number of frames, x, y, channels], so I think the number of frames axis is in the wrong position for it to work. I should make this more robust, like allowing you to provide your own axis ordering.
