### ISSUE TITLE
A Error when running "calculation"

### ISSUE THREAD

**Issue by PhysXu** [din14970/pyMatchSeries#9]
Hi,
I met a problem when running the "calculation", please see below:
![image](https://github.com/din14970/pyMatchSeries/assets/35793078/1a12f675-fc3d-4baf-8a62-ae3ed2531e66)

The operating system of my computer is 'Windows 10 Pro Education (64-bit)' and regional format is 'English (United States)'.
I do not know what would cause this problem above.
Any reply will be appreciated very much.

**Comment by din14970** [comment]
path is set automatically on calling the constructor. 

```python
calculation = MatchSeries(data[5])
```

It is an absolute path to a directory which is already prepopulated with things like a default config file. If you change the path variable, obviously nothing is there and it won't work. If you want to set the path, you must set it when you create a new MatchSeries calculation.

```python
calculation = MatchSeries(data[5], path=...)
```

**Comment by PhysXu** [comment]
> path is set automatically on calling the constructor.
> 
> ```python
> calculation = MatchSeries(data[5])
> ```
> 
> It is an absolute path to a directory which is already prepopulated with things like a default config file. If you change the path variable, obviously nothing is there and it won't work. If you want to set the path, you must set it when you create a new MatchSeries calculation.
> 
> ```python
> calculation = MatchSeries(data[5], path=...)
> ```

Thanks very much for your reply.
It works.
